# Generated by Django 4.0.4 on 2022-07-25 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('singer', models.CharField(max_length=256)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('genre', models.CharField(choices=[('발라드', '발라드'), ('댄스', '댄스'), ('록', '록'), ('OST', 'OST'), ('인디', '인디'), ('POP', 'POP'), ('클래식', '클래식'), ('재즈', '재즈'), ('KPOP', 'KPOP'), ('CCM', 'CCM'), ('힙합', '힙합'), ('블루스', '블루스')], max_length=16)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo_comments', to='musicapp.memo')),
            ],
        ),
    ]
