# Generated by Django 4.0.4 on 2022-07-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_memo_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='likes',
        ),
        migrations.AddField(
            model_name='memo',
            name='likes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
