# Generated by Django 4.0.4 on 2022-07-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_remove_memo_likes_memo_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='null', max_length=512),
        ),
        migrations.AlterField(
            model_name='memo',
            name='author',
            field=models.CharField(default='null', max_length=512),
        ),
    ]
