# Generated by Django 4.0.4 on 2022-07-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_alter_comment_author_alter_memo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='box',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='memo',
            name='author',
            field=models.CharField(max_length=512),
        ),
    ]
