# Generated by Django 4.0.4 on 2022-07-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_remove_comment_author_remove_memo_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='comment_user',
        ),
        migrations.RenameField(
            model_name='memo',
            old_name='memo_author',
            new_name='memo_user',
        ),
    ]
