# Generated by Django 4.0.4 on 2022-07-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_rename_comment_author_comment_comment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user',
            new_name='comment_writer',
        ),
        migrations.RenameField(
            model_name='memo',
            old_name='memo_user',
            new_name='memo_writer',
        ),
    ]
