# Generated by Django 4.0.4 on 2022-07-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_rename_comment_user_comment_comment_writer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_writer',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='memo_writer',
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.CharField(default='null', max_length=512),
        ),
        migrations.AddField(
            model_name='memo',
            name='writer',
            field=models.CharField(default='멋쟁이 사자', max_length=512),
        ),
    ]
