# Generated by Django 4.0.4 on 2022-07-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_memo_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='writer',
        ),
    ]
