# Generated by Django 4.0.4 on 2022-07-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0013_comment_box_alter_memo_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='box',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='box',
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.CharField(default='null', max_length=512),
        ),
        migrations.AddField(
            model_name='memo',
            name='writer',
            field=models.CharField(default='멋쟁이 사자', max_length=512),
        ),
    ]
