# Generated by Django 4.0.4 on 2022-07-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0014_remove_comment_box_remove_memo_box_comment_writer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='writer',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='null', max_length=512),
        ),
        migrations.AddField(
            model_name='memo',
            name='author',
            field=models.CharField(default='멋쟁이 사자', max_length=512),
        ),
    ]
