# Generated by Django 4.0.4 on 2022-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0015_remove_comment_writer_remove_memo_writer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='nickname',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
