# Generated by Django 4.0.4 on 2022-07-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0016_comment_nickname_memo_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='memo_id',
            field=models.IntegerField(null=True),
        ),
    ]
